name: Feature request
description: Suggest an idea
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: Idea
      description: What would you like to see, and why?
    validations:
      required: true
